# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-14 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0011_item_completed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
